# Flow of algorithmn:-


# 1. Importing necessary libraries and dataset.


# 2. Preparing X and Y variables.


# 3. Importing necessary ML algorithmn, here LogisticRegression.


# 4. train given data.


# 5. predict new data.


# 6. calculate the score.

In [4]:
# Importing necessary libraries.

import sklearn
import pandas as pd
import numpy as np

In [5]:
#Reading the csv file and storing it in a dataframe named df.

df = pd.read_csv('IRIS.csv')


In [6]:
#Prints first 5 values.

df.head() 

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
#Displays the first 5 values of cloumn species.

df['Species'].head() 

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [8]:
#Displays the count of individual type of species.

df['Species'].value_counts() 

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [9]:
#Creation of the input variable which contain the features of each flower which would then be used for predicting the type of species.

X = df[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']] 

In [10]:
#Creation of the output variable which contains the target column which we have to predict.

Y = df[['Species']]

In [12]:
#Importing train_test_split

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.25, random_state = 0)

In [13]:
len(df['Species'])

150

In [14]:
len(X_train) #Number of X_train samples. 112 since 75% of 150 = 112.

112

In [15]:
len(X_test) #Number of X_test samples. 38 since 25% of 150 = 38.

38

In [16]:
len(Y_test) #Number of Y_test samples. 38 since 25% of 150 = 38.

38

In [17]:
#Importing the necessary ML algo. Here, we import LogisticRegression algorithmn.

from sklearn.linear_model import LogisticRegression


#Object creation of LogisticRegression algorithmn. 

lr = LogisticRegression()

In [18]:
#Training the model.

lr.fit(X_train,Y_train) 

C:\Anaconda\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [20]:
#Predicting single instance.

lr.predict([[5.1, 3.5, 1.4, 0.2]])

array(['Iris-setosa'], dtype=object)

In [21]:
#Predicting multiple instances.

predicted = lr.predict(X_test)

In [22]:
#Displayes predicted array.

predicted

array(['Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [23]:
#Creating a dataframe named expected.

expected = Y_test 

In [24]:
expected

Species
114   Iris-virginica
62   Iris-versicolor
33       Iris-setosa
107   Iris-virginica
7        Iris-setosa
100   Iris-virginica
40       Iris-setosa
86   Iris-versicolor
76   Iris-versicolor
71   Iris-versicolor
134   Iris-virginica
51   Iris-versicolor
73   Iris-versicolor
54   Iris-versicolor
63   Iris-versicolor
37       Iris-setosa
78   Iris-versicolor
90   Iris-versicolor
45       Iris-setosa
16       Iris-setosa
121   Iris-virginica
66   Iris-versicolor
24       Iris-setosa
8        Iris-setosa
126   Iris-virginica
22       Iris-setosa
44       Iris-setosa
97   Iris-versicolor
93   Iris-versicolor
26       Iris-setosa
137   Iris-virginica
84   Iris-versicolor
27       Iris-setosa
127   Iris-virginica
132   Iris-virginica
59   Iris-versicolor
18       Iris-setosa
83   Iris-versicolor

In [25]:
#Displaying the score.

lr.score(X_test, Y_test)

0.9736842105263158

In [26]:
from sklearn import metrics

In [27]:
#Prints necessary metrics useful in examining and analyzing the model and its performance.

print(metrics.classification_report(expected,predicted))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        13
Iris-versicolor       1.00      0.94      0.97        16
 Iris-virginica       0.90      1.00      0.95         9

       accuracy                           0.97        38
      macro avg       0.97      0.98      0.97        38
   weighted avg       0.98      0.97      0.97        38



In [28]:
#Prints confusion matrix.

print(metrics.confusion_matrix(expected,predicted))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
